---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/rprakashg/quarkus-restapi-starter.git
    app.quarkus.io/build-timestamp: 2022-02-17 - 22:58:38 +0000
    app.quarkus.io/commit-id: db5529585f63d895b2324063f4c917f0ab8726d2
  labels:
    app.kubernetes.io/name: quarkus-restapi-starter
    app.kubernetes.io/version: "1.0"
  name: quarkus-restapi-starter
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-restapi-starter
    app.kubernetes.io/version: "1.0"
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/rprakashg/quarkus-restapi-starter.git
    app.quarkus.io/build-timestamp: 2022-02-17 - 22:58:38 +0000
    app.quarkus.io/commit-id: db5529585f63d895b2324063f4c917f0ab8726d2
  labels:
    app.kubernetes.io/name: quarkus-restapi-starter
    app.kubernetes.io/version: "1.0"
  name: quarkus-restapi-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-restapi-starter
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/rprakashg/quarkus-restapi-starter.git
        app.quarkus.io/build-timestamp: 2022-02-17 - 22:58:38 +0000
        app.quarkus.io/commit-id: db5529585f63d895b2324063f4c917f0ab8726d2
      labels:
        app.kubernetes.io/name: quarkus-restapi-starter
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
      - args:
        - -jar
        - /deployments/quarkus-run.jar
        - -cp
        - /deployments/lib/jakarta.el.jakarta.el-api-3.0.3.jar:/deployments/lib/jakarta.interceptor.jakarta.interceptor-api-1.2.5.jar:/deployments/lib/jakarta.enterprise.jakarta.enterprise.cdi-api-2.0.2.jar:/deployments/lib/jakarta.annotation.jakarta.annotation-api-1.3.5.jar:/deployments/lib/jakarta.transaction.jakarta.transaction-api-1.3.3.jar:/deployments/lib/org.jboss.logging.jboss-logging-3.4.1.Final.jar:/deployments/lib/io.quarkus.arc.arc-1.12.2.Final.jar:/deployments/lib/jakarta.inject.jakarta.inject-api-1.0.jar:/deployments/lib/io.quarkus.quarkus-development-mode-spi-1.12.2.Final.jar:/deployments/lib/io.smallrye.common.smallrye-common-annotation-1.5.0.jar:/deployments/lib/org.eclipse.microprofile.config.microprofile-config-api-1.4.jar:/deployments/lib/io.smallrye.config.smallrye-config-common-1.10.2.jar:/deployments/lib/io.smallrye.common.smallrye-common-function-1.5.0.jar:/deployments/lib/io.smallrye.common.smallrye-common-expression-1.5.0.jar:/deployments/lib/io.smallrye.common.smallrye-common-constraint-1.5.0.jar:/deployments/lib/io.smallrye.common.smallrye-common-classloader-1.5.0.jar:/deployments/lib/io.smallrye.config.smallrye-config-1.10.2.jar:/deployments/lib/org.jboss.logmanager.jboss-logmanager-embedded-1.0.6.jar:/deployments/lib/org.jboss.logging.jboss-logging-annotations-2.2.0.Final.jar:/deployments/lib/org.jboss.threads.jboss-threads-3.2.0.Final.jar:/deployments/lib/org.slf4j.slf4j-api-1.7.30.jar:/deployments/lib/org.jboss.slf4j.slf4j-jboss-logmanager-1.1.0.Final.jar:/deployments/lib/org.graalvm.sdk.graal-sdk-21.0.0.jar:/deployments/lib/org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar:/deployments/lib/io.smallrye.common.smallrye-common-io-1.5.0.jar:/deployments/lib/io.quarkus.quarkus-bootstrap-runner-1.12.2.Final.jar:/deployments/lib/io.quarkus.quarkus-core-1.12.2.Final.jar:/deployments/lib/org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.0.1.jar:/deployments/lib/io.quarkus.quarkus-arc-1.12.2.Final.jar:/deployments/lib/io.quarkus.quarkus-security-runtime-spi-1.12.2.Final.jar:/deployments/lib/io.quarkus.quarkus-vertx-http-dev-console-runtime-spi-1.12.2.Final.jar:/deployments/lib/org.reactivestreams.reactive-streams-1.0.3.jar:/deployments/lib/io.smallrye.reactive.mutiny-0.13.0.jar:/deployments/lib/io.quarkus.security.quarkus-security-1.1.3.Final.jar:/deployments/lib/io.netty.netty-codec-4.1.49.Final.jar:/deployments/lib/io.netty.netty-handler-4.1.49.Final.jar:/deployments/lib/io.quarkus.quarkus-netty-1.12.2.Final.jar:/deployments/lib/io.netty.netty-common-4.1.49.Final.jar:/deployments/lib/io.netty.netty-buffer-4.1.49.Final.jar:/deployments/lib/io.netty.netty-transport-4.1.49.Final.jar:/deployments/lib/io.netty.netty-codec-socks-4.1.49.Final.jar:/deployments/lib/io.netty.netty-handler-proxy-4.1.49.Final.jar:/deployments/lib/io.netty.netty-codec-http-4.1.49.Final.jar:/deployments/lib/io.netty.netty-codec-http2-4.1.49.Final.jar:/deployments/lib/io.netty.netty-resolver-4.1.49.Final.jar:/deployments/lib/io.netty.netty-codec-dns-4.1.49.Final.jar:/deployments/lib/io.netty.netty-resolver-dns-4.1.49.Final.jar:/deployments/lib/io.vertx.vertx-core-3.9.5.jar:/deployments/lib/io.quarkus.quarkus-vertx-core-1.12.2.Final.jar:/deployments/lib/io.vertx.vertx-web-common-3.9.5.jar:/deployments/lib/io.vertx.vertx-auth-common-3.9.5.jar:/deployments/lib/io.vertx.vertx-bridge-common-3.9.5.jar:/deployments/lib/io.vertx.vertx-web-3.9.5.jar:/deployments/lib/io.quarkus.quarkus-vertx-http-1.12.2.Final.jar:/deployments/lib/org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-core-spi-4.5.9.Final.jar:/deployments/lib/com.ibm.async.asyncutil-0.1.0.jar:/deployments/lib/org.jboss.resteasy.resteasy-core-4.5.9.Final.jar:/deployments/lib/com.sun.activation.jakarta.activation-1.2.1.jar:/deployments/lib/io.quarkus.quarkus-resteasy-common-1.12.2.Final.jar:/deployments/lib/jakarta.validation.jakarta.validation-api-2.0.2.jar:/deployments/lib/io.quarkus.quarkus-resteasy-server-common-1.12.2.Final.jar:/deployments/lib/io.quarkus.quarkus-resteasy-1.12.2.Final.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-databind-2.12.1.jar:/deployments/lib/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.12.1.jar:/deployments/lib/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.12.1.jar:/deployments/lib/com.fasterxml.jackson.module.jackson-module-parameter-names-2.12.1.jar:/deployments/lib/io.quarkus.quarkus-jackson-1.12.2.Final.jar:/deployments/lib/org.glassfish.jaxb.txw2-2.3.3-b02.jar:/deployments/lib/com.sun.istack.istack-commons-runtime-3.0.10.jar:/deployments/lib/org.glassfish.jaxb.jaxb-runtime-2.3.3-b02.jar:/deployments/lib/org.jboss.resteasy.resteasy-jaxb-provider-4.5.9.Final.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-core-2.12.1.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-annotations-2.12.1.jar:/deployments/lib/com.fasterxml.jackson.jaxrs.jackson-jaxrs-base-2.12.1.jar:/deployments/lib/jakarta.activation.jakarta.activation-api-1.2.1.jar:/deployments/lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.12.1.jar:/deployments/lib/com.fasterxml.jackson.jaxrs.jackson-jaxrs-json-provider-2.12.1.jar:/deployments/lib/com.github.java-json-tools.btf-1.3.jar:/deployments/lib/com.github.java-json-tools.msg-simple-1.2.jar:/deployments/lib/com.github.java-json-tools.jackson-coreutils-2.0.jar:/deployments/lib/com.github.java-json-tools.json-patch-1.13.jar:/deployments/lib/org.jboss.resteasy.resteasy-jackson2-provider-4.5.9.Final.jar:/deployments/lib/org.jboss.spec.javax.xml.bind.jboss-jaxb-api_2.3_spec-2.0.0.Final.jar:/deployments/lib/io.quarkus.quarkus-resteasy-jackson-1.12.2.Final.jar:/deployments/lib/org.eclipse.yasson-1.0.8.jar:/deployments/lib/io.quarkus.quarkus-jsonb-1.12.2.Final.jar:/deployments/lib/org.glassfish.jakarta.json-1.1.6.jar:/deployments/lib/jakarta.json.bind.jakarta.json.bind-api-1.0.2.jar:/deployments/lib/org.jboss.resteasy.resteasy-json-binding-provider-4.5.9.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-json-p-provider-4.5.9.Final.jar:/deployments/lib/commons-io.commons-io-2.8.0.jar:/deployments/lib/io.quarkus.quarkus-resteasy-jsonb-1.12.2.Final.jar:/deployments/lib/org.projectlombok.lombok-1.18.22.jar:/deployments/lib/org.eclipse.microprofile.health.microprofile-health-api-2.2.jar:/deployments/lib/io.smallrye.smallrye-health-api-2.2.6.jar:/deployments/lib/io.smallrye.smallrye-health-2.2.6.jar:/deployments/lib/io.smallrye.smallrye-health-provided-checks-2.2.6.jar:/deployments/lib/io.quarkus.quarkus-jsonp-1.12.2.Final.jar:/deployments/lib/io.quarkus.quarkus-smallrye-health-1.12.2.Final.jar:/deployments/lib/io.quarkus.quarkus-kubernetes-client-internal-1.12.2.Final.jar:/deployments/lib/io.quarkus.quarkus-openshift-1.12.2.Final.jar
        - -Dquarkus.http.host=0.0.0.0
        - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
        command:
        - java
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_LIB_DIR
          value: /deployments/lib
        - name: JAVA_APP_JAR
          value: /deployments/quarkus-run.jar
        image: image-registry.openshift-image-registry.svc:5000/test/quarkus-restapi-starter:1.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: quarkus-restapi-starter
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
